"""dexbuf: Fast, 0-copy, and complete Dalvik Executable (DEX) reader.

Built on Python's Buffer protocol (collections.abc.Buffer) and typed dataclasses.
Provides low-level spec representations and a tiered, REPL-friendly API.
"""

from dexbuf.debug import (
    DebugInstruction,
    DebugOpcode,
    DebugPosition,
)
from dexbuf.instructions import IOP, Instruction, Opcode, Payload
from dexbuf.items import (
    AnnotationItem,
    AnnotationOffItem,
    AnnotationsDirectoryItem,
    AnnotationSetItem,
    AnnotationSetRefItem,
    AnnotationSetRefList,
    AnnotationVisibility,
    CallSiteIdItem,
    ClassDataItem,
    ClassDefItem,
    CodeItem,
    DebugInfoItem,
    EncodedArrayItem,
    EncodedCatchHandler,
    EncodedCatchHandlerList,
    EncodedField,
    EncodedMethod,
    EncodedTypeAddrPair,
    FieldAnnotation,
    FieldIdItem,
    HiddenapiClassDataItem,
    HiddenapiRestrictionFlag,
    MethodAnnotation,
    MethodHandleItem,
    MethodIdItem,
    ParameterAnnotation,
    ProtoIdItem,
    StringDataItem,
    StringIdItem,
    TryItem,
    TypeIdItem,
    TypeList,
)
from dexbuf.types import (
    NO_INDEX,
    NO_OFFSET,
    ArgumentCount,
    BranchOffset,
    Count,
    Hat,
    Idx,
    Literal,
    Offset,
    Reg,
)
from dexbuf.value import (
    AnnotationElement,
    EncodedAnnotation,
    EncodedArray,
    EncodedValue,
    ValueType,
)

__version__ = "0.1.0.dev0"

__all__ = [
    "IOP",
    "NO_INDEX",
    "NO_OFFSET",
    "AnnotationElement",
    "AnnotationItem",
    "AnnotationOffItem",
    "AnnotationSetItem",
    "AnnotationSetRefItem",
    "AnnotationSetRefList",
    "AnnotationVisibility",
    "AnnotationsDirectoryItem",
    "ArgumentCount",
    "BranchOffset",
    "CallSiteIdItem",
    "ClassDataItem",
    "ClassDefItem",
    "CodeItem",
    "Count",
    "DebugInfoItem",
    "DebugInstruction",
    "DebugOpcode",
    "DebugPosition",
    "EncodedAnnotation",
    "EncodedArray",
    "EncodedArrayItem",
    "EncodedCatchHandler",
    "EncodedCatchHandlerList",
    "EncodedField",
    "EncodedMethod",
    "EncodedTypeAddrPair",
    "EncodedValue",
    "FieldAnnotation",
    "FieldIdItem",
    "Hat",
    "HiddenapiClassDataItem",
    "HiddenapiRestrictionFlag",
    "Idx",
    "Instruction",
    "Literal",
    "MethodAnnotation",
    "MethodHandleItem",
    "MethodIdItem",
    "Offset",
    "Opcode",
    "ParameterAnnotation",
    "Payload",
    "ProtoIdItem",
    "Reg",
    "StringDataItem",
    "StringIdItem",
    "TryItem",
    "TypeIdItem",
    "TypeList",
    "ValueType",
    "__version__",
]
